[project]
name = "finchdraw"
version = "0.1.0"
description = "Draw where a Finch robot would move as a diagram"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.6.0",
    "jupyterlab>=4.4.9",
]
